# Project information
site_name: FSDS-DVC-NLP-project-with-docs

#define TOC or order of website
nav:
  - Home: index.md
  - Data-prep-stage: data_prep.md

site_author: Mohammad Usama
site_description: >-
  Steps to a NLP project
  
# Repository
repo_name: mohammadusama2/DVC-NLP-project-docs-template
repo_url: https://github.com/mohammadusama2/DVC-NLP-project-docs-template

# Configuration
theme:
  name: material
  features:
    - tabs
  language: en
  palette:
    primary: green
    accent: green

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mohammadusama2
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tufz_usama
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mohdusama
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/tufz_usama/

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
