# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_DATA_TRAIN: train.pkl
  FEATURIZED_DATA_TEST: test.pkl
  TRAINED_MODEL_DIR: model
  MODEL_DIR: model
  MODEL_NAME: model.h5

metrics:
  SCORES: scores.json

plots:
  PRC: prc.json  #Precision-Recall Curve
  ROC: roc.json  #Reciever Operator Characteristic Curve

source_Data:
  # git-lfs required for cloning large file directory from github
  # git-lfs has limitation of file download size
  URL: https://raw.githubusercontent.com/c17hawke/commom-data-repo/main/data.xml 
  data_dir: data
  data_file: data.xml